version: '3.8'

services:
  app:
    build: .
    container_name: antriantpt_app
    restart: unless-stopped
    environment:
      DATABASE_URL: ${DATABASE_URL}
      SECRET_KEY: ${JWT_SECRET}
      NODE_ENV: production
      PORT: 3000
    ports:
      - "3003:3000"
    networks:
      - antriantpt_network

networks:
  antriantpt_network:
    driver: bridge